language: java
install: true

os: linux
dist: trusty
jdk: oraclejdk11

services: mongodb


cache:
  directories:
    - $HOME/.gradle

script:
  - ./gradlew build

notifications:
  email:
    recipients:
      - egnaf@yahoo.com
      - hardelele@yahoo.com
    on_success: never
    on_failure: always
