language: java
install: true

os: linux
dist: trusty
jdk: oraclejdk8

cache:
  directories:
#    - $HOME/.gradle

script:
  - rm -rf .gradle
  - gradle wrapper --gradle-version 6.5 --distribution-type all
  - ./gradlew build

notifications:
  email:
    recipients:
      - egnaf@yahoo.com
      - hardelele@yahoo.com
    on_success: never
    on_failure: always
