--- # cloud # ---
server:
  port: 8080

spring:
  profiles: cloud
  data:
    mongodb:
      host: mongodb
      port: 27017


--- # staging # ---
server:
  port: 9003

spring:
  profiles: staging
  data:
    mongodb:
      database: post-staging


--- # develop # ---
server:
  port: 9002

spring:
  profiles:
    active: develop
  data:
    mongodb:
      database: post-develop


# example
#
# spring:
#   data:
#     mongodb:
#       database: 1
#       database: 2
#       username: 3
#       password: 4
