--- # cloud # ---
server:
  port: 8080

spring:
  profiles: cloud
  data:
    mongodb:
      host: mongodb
      port: 27017
      database: sampledb
      username: userX0W
      password: CbAk3J7f2FTxA6EF


--- # staging # ---
server:
  port: 9003

spring:
  profiles: staging

MONGO_URI: mongodb://127.0.0.1
MONGO_PORT: 27017
MONGO_DBNAME: mongo-staging


--- # develop # ---
server:
  port: 9002

spring:
  profiles:
    active: develop

MONGO_URI: mongodb://127.0.0.1
MONGO_PORT: 27017
MONGO_DBNAME: mongo-develop
