server:
  port: 9002

spring:
  profiles:
    active: develop

  data:
    mongodb:
      uri: mongodb://localhost:27017/mongo-local

MONGO_URI: mongodb://127.0.0.1
MONGO_PORT: 27017
MONGO_DBNAME: mongo-develop

---

server:
  port: 9003

spring:
  profiles:
    active: staging

    data:
      mongodb:
        uri: mongodb://localhost:27017/mongo-local

MONGO_URI: mongodb://127.0.0.1
MONGO_PORT: 27018
MONGO_DBNAME: mongo-staging


---

server:
  port: 9004

spring:
  profiles:
    active: cloud

    data:
      mongodb:
        uri: mongodb://localhost:27017/mongo-local

MONGO_URI: mongodb://127.0.0.1
MONGO_PORT: 27019
MONGO_DBNAME: mongo-cloud

