--- # cloud # ---
server:
  port: 8080

spring:
  profiles: cloud
  data:
    mongodb:
      authentication-database: admin
      host: mongo
      port: 27017
      database: sampledb
      username: userX0W
      password: CbAk3J7f2FTxA6EF


--- # staging # ---
server:
  port: 9003

spring:
  profiles: staging
  data:
    mongodb:
      database: post-staging


--- # develop # ---
server:
  port: 9002

spring:
  profiles:
    active: develop
  data:
    mongodb:
      database: post-develop
