name: deploy

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Install MongoDB 4.2
        uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: 4.2

      - name: Gradle build
        run: gradle build

      - name: Create a docker image
        run: bash ./config/docker/create_image.sh

      - name: Log into registry
        run: docker login --username=reckue --password=${{ secrets.DOCKER_PASSWORD }}

      - name: Docker push
        run: bash ./config/docker/push_image.sh

      - name: Deploy
        uses: redhat-developer/openshift-actions@v1.1
        with:
          version: 'latest'
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER_URL }}
          parameters: '{"apitoken": "${{ secrets.API_TOKEN }}", "acceptUntrustedCerts": "true"}'
          cmd: |
            'version'
            'delete -f ./config/k8s/template.yaml'
            'create -f ./config/k8s/template.yaml'
