name: Piplelines

on:
  push:
    branches:
      - master
      - develop
      - ISSUE-*
  pull_request:
    branches:
      - master
      - develop
      - ISSUE-*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Start MongoDB 4.2
        uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: 4.2

      - name: Build
        run: gradle build
